name: Tests

on:
  pull_request:
    types: [opened, closed]

jobs:
  test:
    if: github.event.action != 'closed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset linux-debug

      - name: Build
        run: cmake --build --preset linux-debug --parallel

      - name: Run tests
        run: ctest --preset linux-debug